---
- name: Chrony Configuration 
  hosts: all
  tasks:
  - name: Install chrony package
    package:
      name: chrony # required. Package name, or package specifier with version. Syntax varies with package manager. For example C(name-1.0) or C(name=1.0). Package names also vary with package manager; this module will not "translate" them per distro. For example C(libyaml-dev), C(libyaml-devel).
      state: present # required. Whether to install (C(present)), or remove (C(absent)) a package. You can use other states like C(latest) ONLY if they are supported by the underlying package module(s) executed.
      use: auto # not required. The required package manager module to use (yum, apt, etc). The default 'auto' will use existing facts or try to autodetect it. You should only use this field if the automatic selection is not working for some reason.
  
  - name: Change tizezone to India
    timezone:
      name: Asia/Kolkata # not required. Name of the timezone for the system clock. Default is to keep current setting. B(At least one of name and hwclock are required.)
      hwclock: local # not required. choices: local;UTC. Whether the hardware clock is in UTC or in local timezone. Default is to keep current setting. Note that this option is recommended not to change and may fail to configure, especially on virtual environments such as AWS. B(At least one of name and hwclock are required.) I(Only used on Linux.)
  
  - name: Copy the Configuration file for ntp
    copy:
      src: chrony_rhel.conf
      dest: /etc/chrony.conf
    when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "RedHat" or ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "CentOS"
    notify: restart chrony

  - name: Copy the Configuration file to Ubuntu or Debian based system
    copy:
      dest: /etc/chrony/chrony.conf # required. Remote absolute path where the file should be copied to. If C(src) is a directory, this must be a directory too. If C(dest) is a non-existent path and if either C(dest) ends with "/" or C(src) is a directory, C(dest) is created. If I(dest) is a relative path, the starting directory is determined by the remote host. If C(src) and C(dest) are files, the parent directory of C(dest) is not created and the task fails if it does not already exist.
      src: chrony_ubuntu.conf # not required. Local path to a file to copy to the remote server. This can be absolute or relative. If path is a directory, it is copied recursively. In this case, if path ends with "/", only inside contents of that directory are copied to destination. Otherwise, if it does not end with "/", the directory itself with all contents is copied. This behavior is similar to the C(rsync) command line tool.
      backup: yes # not required. Create a backup file including the timestamp information so you can get the original file back if you somehow clobbered it incorrectly.
    when: ansible_distribution == "Ubuntu"  
    notify: restart chrony
  
  handlers:
    - name: restart chrony
      ansible.builtin.service:
        enabled: yes
        name: chronyd
        state: restarted
        use: auto
    