---
- name: Patching the servers
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars: 
    - hold: "yes"
    - unhold: "no"
  tasks:
  - name: Need to delete the cache file before proceeding for Patching
    file:
      path: /var/cache # required. Path to the file being managed.
      state: absent 
  - name: Play for getting the file name containg the proxy details
    find:
      paths: /etc/profile.d
      recurse: yes
      file_type: file
    register: found_files 
    when: ansible_host == '172.17.60.137'

  - name: comment out the specific lines in the file
    lineinfile:
      path: "{{ item.path }}"
      backup: yes
      regexp: '(export http_proxy=http://172.23.37.4:8080)'
      line: '#\1'
      backrefs: yes
    loop: "{{ found_files.files }}"
    when: ansible_host == '172.17.60.137'

  - name: comment out the specific lines in the file
    lineinfile:
      path: "{{ item.path }}"
      backup: yes
      regexp: '(export https_proxy=http://172.23.37.4:8080)'
      line: '#\1'
      backrefs: yes
    loop: "{{ found_files.files }}"
    when: ansible_host == '172.17.60.137'

  
  - name: Re-Registering the centos 7 servers to foreman
    redhat_subscription:
        state: present
        activationkey: "CentOS 7 NON PROD"
        org_id: "ReBIT"
        force_register : yes
    when:  ansible_distribution == 'CentOS'

  - name: Re-Registering the Rocky linux 8 servers to foreman
    redhat_subscription:
        state: present
        activationkey: "Rocky Linux 8"
        org_id: "ReBIT"
        force_register : yes
    when:  ansible_distribution == 'Rocky'
  
  - name: check the GUI is installed on the ubuntu server
    command: dpkg-query --show xorg
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
    register: dpkg_query_result

    
  - name: Re-Registering the ubuntu desktop to foreman
    redhat_subscription:
        state: present
        activationkey: "Ubuntu 20.04 Development Desktop"
        org_id: "ReBIT"
        force_register : yes
    when:  ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04' and dpkg_query_result.rc == 0

  - name: Re-Registering the ubuntu servers to foreman
    redhat_subscription:
        state: present
        activationkey: "ubuntu2004server_nonprod"
        org_id: "ReBIT"
        force_register : yes
    when:  ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04' and dpkg_query_result.rc != 0
  
  - name: To hold the kernel pacthing for ubuntu
    shell: apt-mark hold $(uname -r)
    when:  ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04' and hold == "yes"
  
  - name: To hold the kernel pacthing for ubuntu
    shell: sudo apt-mark unhold $(apt-mark showhold)
    when:  ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04' and unhold== "yes"
  

  
      