---
- name: Subscription Playbook 
  hosts: all 
  tasks:
  - name: Subscription for Red Hat bases systems
    redhat_subscription:
      state: present # not required. choices: present;absent. whether to register and subscribe (C(present)), or unregister (C(absent)) a system
      username: rajkumar.madnoli  # not required. access.redhat.com or Sat6  username
      password: asdasdsdasd@2021  # not required. access.redhat.com or Sat6 password
      #auto_attach: no # not required. Upon successful registration, auto-consume available subscriptions Added in favor of deprecated autosubscribe in 2.5.
      pool: 
      pool_ids: [] # not required. Specify subscription pool IDs to consume. Prefer over I(pool) when possible as it is much faster.
      force_register: yes # not required. Register the system even if it is already registered
    when: ansible_distribution == "RedHat"

  - name: Subscription for CentOS 7 system
    - name: Description
      community.general.redhat_subscription:
        activationkey: string
        auto_attach: false
        consumer_id: string
        consumer_name: string
        consumer_type: string
        environment: string
        force_register: false
        org_id: string
        password: string
        pool: ^
        pool_ids:
          - element
        release: string
        rhsm_baseurl: string
        rhsm_repo_ca_cert: string
        server_hostname: string
        server_insecure: string
        server_port: string
        server_prefix: string
        server_proxy_hostname: string
        server_proxy_password: string
        server_proxy_port: string
        server_proxy_scheme: string
        server_proxy_user: string
        state: present
        token: string
        username: string
    
  