---
- name: Playbook for User Cretation
  hosts:  localhost
  vars:
    username: vmpg
    password: "L!nux@123"
  tasks:
  - name: Create user
    user:
      name: "{{username}}"
      state: present
      shell: /bin/bash
      createhome: yes
      home: /home/"{{username}}"
      password: "{{ password | pasword_hash('sha512')}}"
      update_password: on_create 
    ignore_errors: yes
    become: yes
  - name: copy the suoders file 
    copy:
      dest: /etc/suoders.d/ 
      src: /home/rebit/Documents/Ansible/ansadmin 
    ignore_errors: yes  
  - name: Creating the .ssh directory 
    file:
      path: /home/"{{ username }}"  
      state: directory 
      mode: 0700  
      owner: "{{ username}}" 
      group: "{{ username}}" 
    ignore_errors: yes  
  - name: Creating the file authorized_key
    file:
      path: /home/"{{username}}/.ssh/authorized_keys 
      state: touch 
      mode: 0600 
      owner: "{{ username }}"  
      group: "{{ username }}" 
    ignore_errors: yes  
    